[technote]
id = "SMTN-016"
series_id = "SMTN"
canonical_url = "https://smtn-016.lsst.io/"
github_url = "https://github.com/lsst-sims/smtn-016"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "Peter", family = "Yoachim"}
internal_id = "yoachimp"
orcid = "https://orcid.org/0000-0003-2874-6464"
[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
address = "Dept. of Astronomy, Box 351580, Seattle, WA 98195, USA"
